/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.ArrayList;
/**
 *
 * @author basilestortz
 */
public class fenetrequiz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(fenetrequiz.class.getName());
    private ArrayList<Question> questions; // pour stocker toutes les questions
    private int indexQuestionCourante = 0; // pour suivre la question courante
    private int scoreValue = 0; 
    
    private void questionSuivante() {
    // Incrémente l'index de la question courante
    indexQuestionCourante++;

    // Vérifie si on est encore dans les limites de la liste de questions
    if(indexQuestionCourante < questions.size()) {
        // Affiche la nouvelle question
        afficherQuestionCourante();
    } else {
        // Si plus de questions, affiche le résultat final
        txt_question.setText("Quiz terminé !");
        feedback.setText("Score final : " + scoreValue + " / " + questions.size());

        // Désactive tous les boutons de réponse
        rep1.setEnabled(false);
        rep2.setEnabled(false);
        rep3.setEnabled(false);
        rep4.setEnabled(false);

        // Désactive le bouton "Question suivante"
        quest_suiv.setEnabled(false);
    }
}
    
    
    
    
    private void verifierReponse(int numeroChoisi) {
    // Récupère la question courante
    Question q = questions.get(indexQuestionCourante);

    // Vérifie si la réponse choisie est correcte
    if(numeroChoisi == q.getIndexBonneReponse()) {
        feedback.setText("Bonne réponse !");
        scoreValue++; // incrémente le score
    } else {
        feedback.setText("Mauvaise réponse !");
    }

    // Désactive tous les boutons pour éviter plusieurs clics
    rep1.setEnabled(false);
    rep2.setEnabled(false);
    rep3.setEnabled(false);
    rep4.setEnabled(false);

    // Met à jour l'affichage du score
    scoreactu.setText("Score : " + scoreValue);
}
    
    
    
    
    
    private void afficherQuestionCourante() {
    // Récupère la question courante
    Question q = questions.get(indexQuestionCourante);

    // Met à jour le texte de la question
    txt_question.setText(q.getIntitule());

    // Met à jour les boutons avec les propositions
    rep1.setText(q.getProposition1());
    rep2.setText(q.getProposition2());
    rep3.setText(q.getProposition3());
    rep4.setText(q.getProposition4());

    // Réactive les boutons (au cas où ils étaient désactivés)
    rep1.setEnabled(true);
    rep2.setEnabled(true);
    rep3.setEnabled(true);
    rep4.setEnabled(true);

    // Réinitialise le feedback
    feedback.setText("");
}
   
    
    /**
     * Creates new form fenetrequiz
     */
    public fenetrequiz() {
      
        initComponents();
        questions = new ArrayList<>();
        
        questions.add(new Question("Quel est le prénom de mbappé?", "Kylian","Michael","Antoine","Giroud",1));
        questions.add(new Question("Qui a gagné la LDC en 2019?", "Barcelone","Bayern","Liverpool","PSG",3));
        questions.add(new Question("Qui a eu le ballon d'OR en 2022?", "Messi","Haaland","Mbappé","Benzema",1));
        questions.add(new Question("Quel joueur n'est pas francais ?", "Maignan","Laporte","Olise","Tolisso",2));
        questions.add(new Question("Quel est le meilleur club du monde ?", "L'OL","Real madrid","Montpellier","Manchester united",1));
        
        afficherQuestionCourante();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_question = new javax.swing.JLabel();
        rep1 = new javax.swing.JButton();
        rep2 = new javax.swing.JButton();
        rep3 = new javax.swing.JButton();
        rep4 = new javax.swing.JButton();
        feedback = new javax.swing.JLabel();
        quest_suiv = new javax.swing.JButton();
        scoreactu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_question.setFont(new java.awt.Font("Helvetica Neue", 0, 70)); // NOI18N
        txt_question.setForeground(new java.awt.Color(255, 0, 0));
        txt_question.setText("question");

        rep1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        rep1.setForeground(new java.awt.Color(0, 0, 255));
        rep1.setText("reponse 1");
        rep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep1ActionPerformed(evt);
            }
        });

        rep2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        rep2.setForeground(new java.awt.Color(0, 0, 255));
        rep2.setText("reponse 2");
        rep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep2ActionPerformed(evt);
            }
        });

        rep3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        rep3.setForeground(new java.awt.Color(0, 0, 255));
        rep3.setText("reponse 3");
        rep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep3ActionPerformed(evt);
            }
        });

        rep4.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        rep4.setForeground(new java.awt.Color(0, 0, 255));
        rep4.setText("reponse4");
        rep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep4ActionPerformed(evt);
            }
        });

        feedback.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 2, 36)); // NOI18N
        feedback.setForeground(new java.awt.Color(204, 0, 204));
        feedback.setText("feedback");

        quest_suiv.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        quest_suiv.setText("question suivante");
        quest_suiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest_suivActionPerformed(evt);
            }
        });

        scoreactu.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        scoreactu.setText("score");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186)
                        .addComponent(quest_suiv, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_question, javax.swing.GroupLayout.PREFERRED_SIZE, 1118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rep1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(rep2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(rep3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(rep4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(315, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(scoreactu, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(364, 364, 364))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(scoreactu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(txt_question, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rep1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rep2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rep3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rep4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addComponent(quest_suiv)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep2ActionPerformed
        verifierReponse(2);
    }//GEN-LAST:event_rep2ActionPerformed

    private void rep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep1ActionPerformed
        verifierReponse(1);
       
    }//GEN-LAST:event_rep1ActionPerformed

    private void rep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep3ActionPerformed
        // TODO add your handling code here:
        verifierReponse(3);
    }//GEN-LAST:event_rep3ActionPerformed

    private void rep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep4ActionPerformed
        // TODO add your handling code here:
        verifierReponse(4);
    }//GEN-LAST:event_rep4ActionPerformed

    private void quest_suivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest_suivActionPerformed
        // TODO add your handling code here:
        questionSuivante();
    }//GEN-LAST:event_quest_suivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new fenetrequiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel feedback;
    private javax.swing.JButton quest_suiv;
    private javax.swing.JButton rep1;
    private javax.swing.JButton rep2;
    private javax.swing.JButton rep3;
    private javax.swing.JButton rep4;
    private javax.swing.JLabel scoreactu;
    private javax.swing.JLabel txt_question;
    // End of variables declaration//GEN-END:variables
}
