/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author basilestortz
 */
public class interfacegraphique extends javax.swing.JFrame {
    
    int nbClics=0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interfacegraphique.class.getName());

    /**
     * Creates new form interfacegraphique
     */
    public interfacegraphique() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_bienvenue = new javax.swing.JLabel();
        bouton_ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_bienvenue.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 2, 12)); // NOI18N
        txt_bienvenue.setForeground(new java.awt.Color(255, 0, 0));
        txt_bienvenue.setText("bonjour ");

        bouton_ok.setText("ok");
        bouton_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bouton_okMouseEntered(evt);
            }
        });
        bouton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bouton_ok)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txt_bienvenue, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txt_bienvenue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(bouton_ok)
                .addGap(0, 87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_okActionPerformed
        if (nbClics == 0 )txt_bienvenue.setText("");
        if (nbClics == 1 )txt_bienvenue.setText("selem ");
        if (nbClics == 2 )txt_bienvenue.setText("selem les ");
        if (nbClics == 3 )txt_bienvenue.setText("selem les rhho ");
        if (nbClics == 4 )txt_bienvenue.setText("selem les rhho benderho");
        nbClics++;
    }//GEN-LAST:event_bouton_okActionPerformed

    private void bouton_okMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bouton_okMouseEntered
       bouton_ok.setText("clique pas");
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_okMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interfacegraphique().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_ok;
    private javax.swing.JLabel txt_bienvenue;
    // End of variables declaration//GEN-END:variables
}
