/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author basilestortz
 */
public class métier extends javax.swing.JFrame {
    private int[] chiffres = {0, 0, 0, 0};
    private int tentatives = 10 ;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(métier.class.getName());
    
    private int[] codeSecret = new int[4];
    
    private int[] getCombinaisonJoueur() {
    int[] combi = new int[4];
    combi[0] = Integer.parseInt(valeur_chiffre_1.getText());
    combi[1] = Integer.parseInt(valeur_chiffre_2.getText());
    combi[2] = Integer.parseInt(valeur_chiffre_3.getText());
    combi[3] = Integer.parseInt(valeur_chiffre_4.getText());
    return combi;
}
    
    
    private int[] testerCombinaison(int[] joueur) {

    int exact = 0;
    int tropGrand = 0;
    int tropPetit = 0;

    for (int i = 0; i < 4; i++) {
        if (joueur[i] == codeSecret[i]) {
            exact++;
        } else if (joueur[i] > codeSecret[i]) {
            tropGrand++;
        } else {
            tropPetit++;
        }
    }

    return new int[] { exact, tropGrand, tropPetit };
}
    
    
    

    /**
     * Creates new form métier
     */
    public métier() {
        initComponents();
        genererCodeSecret();
    }
    
private void incrementDigit(int idx) {
    chiffres[idx] = (chiffres[idx] + 1) % 10;
    updateDigitLabel(idx);
}

private void decrementDigit(int idx) {
    chiffres[idx] = (chiffres[idx] + 9) % 10; // (digit - 1) modulo 10
    updateDigitLabel(idx);
}

private void updateDigitLabel(int idx) {
    switch (idx) {
        case 0 -> valeur_chiffre_1.setText(String.valueOf(chiffres[0]));
        case 1 -> valeur_chiffre_2.setText(String.valueOf(chiffres[1]));
        case 2 -> valeur_chiffre_3.setText(String.valueOf(chiffres[2]));
        case 3 -> valeur_chiffre_4.setText(String.valueOf(chiffres[3]));
    }
}

private void bloquerBoutons() {
    up_chiffre_1.setEnabled(false);
    up_chiffre_2.setEnabled(false);
    up_chiffre_3.setEnabled(false);
    up_chiffre_4.setEnabled(false);
    down_chiffre_1.setEnabled(false);
    down_chiffre_2.setEnabled(false);
    down_chiffre_3.setEnabled(false);
    down_chiffre_4.setEnabled(false);
    test.setEnabled(false);
}

private void genererCodeSecret() {
    java.util.Random rand = new java.util.Random();
    for (int i = 0; i < 4; i++) {
        codeSecret[i] = rand.nextInt(10); // génère entre 0 et 9
    }

    // (Optionnel - pour tester) : afficher le code secret dans la console
    System.out.println("Code secret généré : " 
        + codeSecret[0] + codeSecret[1] + codeSecret[2] + codeSecret[3]);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        test = new javax.swing.JButton();
        txt_lbl_chiffresexact = new javax.swing.JLabel();
        txt_lbl_chiffretrophaut = new javax.swing.JLabel();
        txt_lbl_chiffretropbas = new javax.swing.JLabel();
        nb_chiffre_exact = new javax.swing.JLabel();
        nb_chiffre_grand = new javax.swing.JLabel();
        nb_chiffre_petit = new javax.swing.JLabel();
        nb_tentatives_restantes = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        recommencer = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        valeur_chiffre_1 = new javax.swing.JLabel();
        valeur_chiffre_2 = new javax.swing.JLabel();
        valeur_chiffre_3 = new javax.swing.JLabel();
        valeur_chiffre_4 = new javax.swing.JLabel();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIgnoreRepaint(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setText("trouve le bon code en moins de 5 tentatives ");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 16, 288, -1));

        test.setFont(new java.awt.Font("Yuppy SC", 0, 24)); // NOI18N
        test.setText("TESTER");
        test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testActionPerformed(evt);
            }
        });
        getContentPane().add(test, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 130, 60));

        txt_lbl_chiffresexact.setText("CHIFFRES EXACT");
        getContentPane().add(txt_lbl_chiffresexact, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 294, -1, -1));

        txt_lbl_chiffretrophaut.setText("CHIFFRES TROP GRANDS ");
        getContentPane().add(txt_lbl_chiffretrophaut, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 358, -1, -1));

        txt_lbl_chiffretropbas.setText("CHIFFRES TROP PETITS");
        getContentPane().add(txt_lbl_chiffretropbas, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 416, -1, -1));

        nb_chiffre_exact.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        nb_chiffre_exact.setText("0");
        getContentPane().add(nb_chiffre_exact, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 289, -1, -1));

        nb_chiffre_grand.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        nb_chiffre_grand.setText("0");
        getContentPane().add(nb_chiffre_grand, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 353, -1, -1));

        nb_chiffre_petit.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        nb_chiffre_petit.setText("0");
        getContentPane().add(nb_chiffre_petit, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 411, -1, -1));

        nb_tentatives_restantes.setText("TENTATIVES ");
        getContentPane().add(nb_tentatives_restantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 250, -1));

        score.setBackground(new java.awt.Color(255, 51, 0));
        score.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score.setText("0 sur 5");
        getContentPane().add(score, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 330, 95));

        recommencer.setText("recommencer");
        getContentPane().add(recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, -1, -1));

        jPanel1.setLayout(new java.awt.GridLayout(3, 4));

        up_chiffre_1.setBackground(new java.awt.Color(0, 255, 0));
        up_chiffre_1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        up_chiffre_1.setText("/\\");
            up_chiffre_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_1ActionPerformed(evt);
                }
            });
            jPanel1.add(up_chiffre_1);

            up_chiffre_2.setBackground(new java.awt.Color(0, 255, 0));
            up_chiffre_2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
            up_chiffre_2.setText("/\\");
                up_chiffre_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up_chiffre_2ActionPerformed(evt);
                    }
                });
                jPanel1.add(up_chiffre_2);

                up_chiffre_3.setBackground(new java.awt.Color(0, 255, 0));
                up_chiffre_3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
                up_chiffre_3.setText("/\\");
                    up_chiffre_3.setBorder(new javax.swing.border.MatteBorder(null));
                    up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up_chiffre_3ActionPerformed(evt);
                        }
                    });
                    jPanel1.add(up_chiffre_3);

                    up_chiffre_4.setBackground(new java.awt.Color(0, 255, 51));
                    up_chiffre_4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
                    up_chiffre_4.setText("/\\");
                        up_chiffre_4.setBorder(new javax.swing.border.MatteBorder(null));
                        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_4ActionPerformed(evt);
                            }
                        });
                        jPanel1.add(up_chiffre_4);

                        valeur_chiffre_1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
                        valeur_chiffre_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        valeur_chiffre_1.setText("0");
                        jPanel1.add(valeur_chiffre_1);

                        valeur_chiffre_2.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
                        valeur_chiffre_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        valeur_chiffre_2.setText("0");
                        jPanel1.add(valeur_chiffre_2);

                        valeur_chiffre_3.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
                        valeur_chiffre_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        valeur_chiffre_3.setText("0");
                        jPanel1.add(valeur_chiffre_3);

                        valeur_chiffre_4.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
                        valeur_chiffre_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        valeur_chiffre_4.setText("0");
                        jPanel1.add(valeur_chiffre_4);

                        down_chiffre_1.setBackground(new java.awt.Color(255, 51, 0));
                        down_chiffre_1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
                        down_chiffre_1.setText("V");
                        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_1ActionPerformed(evt);
                            }
                        });
                        jPanel1.add(down_chiffre_1);

                        down_chiffre_2.setBackground(new java.awt.Color(255, 51, 0));
                        down_chiffre_2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
                        down_chiffre_2.setText("V");
                        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_2ActionPerformed(evt);
                            }
                        });
                        jPanel1.add(down_chiffre_2);

                        down_chiffre_3.setBackground(new java.awt.Color(255, 51, 0));
                        down_chiffre_3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
                        down_chiffre_3.setText("V");
                        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_3ActionPerformed(evt);
                            }
                        });
                        jPanel1.add(down_chiffre_3);

                        down_chiffre_4.setBackground(new java.awt.Color(255, 51, 0));
                        down_chiffre_4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
                        down_chiffre_4.setText("V");
                        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_4ActionPerformed(evt);
                            }
                        });
                        jPanel1.add(down_chiffre_4);

                        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 450, 200));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        // TODO add your handling code here:
        incrementDigit(0);
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        // TODO add your handling code here:
        incrementDigit(1);
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
        // TODO add your handling code here:
        incrementDigit(2);
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
        // TODO add your handling code here:
        incrementDigit(3);
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        // TODO add your handling code here:
        decrementDigit(0);
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
        // TODO add your handling code here:
        decrementDigit(1);
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
        // TODO add your handling code here:
        decrementDigit(2);
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
        // TODO add your handling code here:
        decrementDigit(3);
    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testActionPerformed
        // TODO add your handling code here:
         // Récupérer la combinaison du joueur
        int[] joueur = getCombinaisonJoueur();

    // Tester la combinaison
        int[] resultat = testerCombinaison(joueur);

        int exact = resultat[0];
        int tropGrand = resultat[1];
        int tropPetit = resultat[2];

    // Affichage dans les labels
        nb_chiffre_exact.setText(String.valueOf(exact));
        nb_chiffre_grand.setText(String.valueOf(tropGrand));
        nb_chiffre_petit.setText(String.valueOf(tropPetit));

    // Mise à jour des tentatives
        tentatives--;
        nb_tentatives_restantes.setText(tentatives + " tentatives restantes");
        score.setText((10 - tentatives) + " sur 10 ");

        if (exact == 4) {
        // Joueur a trouvé le code
        javax.swing.JOptionPane.showMessageDialog(this, "Félicitations ! Vous avez trouvé le code !");
        bloquerBoutons(); // désactive tous les boutons
    } else if (tentatives == 0) {
        // Plus de tentatives
        javax.swing.JOptionPane.showMessageDialog(this, "Partie terminée t'es nul ! Le code était : " 
            + codeSecret[0] + codeSecret[1] + codeSecret[2] + codeSecret[3]);
        bloquerBoutons();
    
}

       
         
        
    }//GEN-LAST:event_testActionPerformed

    /**
     * @paramargs the command line arguments
     */
    public static void main(String[] args) {
    // Set the Nimbus look and feel
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace(); // au lieu de logger, pour simplifier
    }

    // Crée et affiche la fenêtre
    javax.swing.SwingUtilities.invokeLater(new Runnable() {
        public void run() {
            new métier().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nb_chiffre_exact;
    private javax.swing.JLabel nb_chiffre_grand;
    private javax.swing.JLabel nb_chiffre_petit;
    private javax.swing.JLabel nb_tentatives_restantes;
    private javax.swing.JButton recommencer;
    private javax.swing.JLabel score;
    private javax.swing.JButton test;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel txt_lbl_chiffresexact;
    private javax.swing.JLabel txt_lbl_chiffretropbas;
    private javax.swing.JLabel txt_lbl_chiffretrophaut;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    private javax.swing.JLabel valeur_chiffre_1;
    private javax.swing.JLabel valeur_chiffre_2;
    private javax.swing.JLabel valeur_chiffre_3;
    private javax.swing.JLabel valeur_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
