/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author basilestortz
 */
public class métier extends javax.swing.JFrame {
    private int[] chiffres = {0, 0, 0, 0};
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(métier.class.getName());
    
    private int[] codeSecret = new int[4];
    
    private int[] getCombinaisonJoueur() {
    int[] combi = new int[4];
    combi[0] = Integer.parseInt(valeur_chiffre_1.getText());
    combi[1] = Integer.parseInt(valeur_chiffre_2.getText());
    combi[2] = Integer.parseInt(valeur_chiffre_3.getText());
    combi[3] = Integer.parseInt(valeur_chiffre_4.getText());
    return combi;
}
    
    
    private int[] testerCombinaison(int[] joueur) {

    int exact = 0;
    int tropGrand = 0;
    int tropPetit = 0;

    for (int i = 0; i < 4; i++) {
        if (joueur[i] == codeSecret[i]) {
            exact++;
        } else if (joueur[i] > codeSecret[i]) {
            tropGrand++;
        } else {
            tropPetit++;
        }
    }

    return new int[] { exact, tropGrand, tropPetit };
}
    
    
    

    /**
     * Creates new form métier
     */
    public métier() {
        initComponents();
        genererCodeSecret();
    }
    
private void incrementDigit(int idx) {
    chiffres[idx] = (chiffres[idx] + 1) % 10;
    updateDigitLabel(idx);
}

private void decrementDigit(int idx) {
    chiffres[idx] = (chiffres[idx] + 9) % 10; // (digit - 1) modulo 10
    updateDigitLabel(idx);
}

private void updateDigitLabel(int idx) {
    switch (idx) {
        case 0 -> valeur_chiffre_1.setText(String.valueOf(chiffres[0]));
        case 1 -> valeur_chiffre_2.setText(String.valueOf(chiffres[1]));
        case 2 -> valeur_chiffre_3.setText(String.valueOf(chiffres[2]));
        case 3 -> valeur_chiffre_4.setText(String.valueOf(chiffres[3]));
    }
}

private void genererCodeSecret() {
    java.util.Random rand = new java.util.Random();
    for (int i = 0; i < 4; i++) {
        codeSecret[i] = rand.nextInt(10); // génère entre 0 et 9
    }

    // (Optionnel - pour tester) : afficher le code secret dans la console
    System.out.println("Code secret généré : " 
        + codeSecret[0] + codeSecret[1] + codeSecret[2] + codeSecret[3]);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        valeur_chiffre_1 = new javax.swing.JLabel();
        valeur_chiffre_2 = new javax.swing.JLabel();
        valeur_chiffre_3 = new javax.swing.JLabel();
        valeur_chiffre_4 = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        test = new javax.swing.JButton();
        txt_lbl_chiffresexact = new javax.swing.JLabel();
        txt_lbl_chiffretrophaut = new javax.swing.JLabel();
        txt_lbl_chiffretropbas = new javax.swing.JLabel();
        nb_chiffre_exact = new javax.swing.JLabel();
        nb_chiffre_grand = new javax.swing.JLabel();
        nb_chiffre_petit = new javax.swing.JLabel();
        nb_tentatives_restantes = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        recommencer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        texte_intro.setText("trouve le bon code en moins de 5 tentatives ");

        valeur_chiffre_1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        valeur_chiffre_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valeur_chiffre_1.setText("0");

        valeur_chiffre_2.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        valeur_chiffre_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valeur_chiffre_2.setText("0");

        valeur_chiffre_3.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        valeur_chiffre_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valeur_chiffre_3.setText("0");

        valeur_chiffre_4.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        valeur_chiffre_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valeur_chiffre_4.setText("0");

        up_chiffre_1.setText("/\\");
            up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_1ActionPerformed(evt);
                }
            });

            up_chiffre_2.setText("/\\");
                up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up_chiffre_2ActionPerformed(evt);
                    }
                });

                up_chiffre_3.setText("/\\");
                    up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up_chiffre_3ActionPerformed(evt);
                        }
                    });

                    up_chiffre_4.setText("/\\");
                        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_4ActionPerformed(evt);
                            }
                        });

                        down_chiffre_1.setText("V");
                        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_1ActionPerformed(evt);
                            }
                        });

                        down_chiffre_2.setText("V");
                        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_2ActionPerformed(evt);
                            }
                        });

                        down_chiffre_3.setText("V");
                        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_3ActionPerformed(evt);
                            }
                        });

                        down_chiffre_4.setText("V");
                        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_4ActionPerformed(evt);
                            }
                        });

                        test.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
                        test.setText("tester");
                        test.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                testActionPerformed(evt);
                            }
                        });

                        txt_lbl_chiffresexact.setText("chiffres exact :");

                        txt_lbl_chiffretrophaut.setText("chiffres trop grand :");

                        txt_lbl_chiffretropbas.setText("chiffres trop petit :");

                        nb_chiffre_exact.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
                        nb_chiffre_exact.setText("0");

                        nb_chiffre_grand.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
                        nb_chiffre_grand.setText("0");

                        nb_chiffre_petit.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
                        nb_chiffre_petit.setText("0");

                        nb_tentatives_restantes.setText("tentatives");

                        score.setBackground(new java.awt.Color(255, 51, 0));
                        score.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
                        score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        score.setText("0 sur 5");

                        recommencer.setText("recommencer");

                        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                        getContentPane().setLayout(layout);
                        layout.setHorizontalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(down_chiffre_1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(nb_chiffre_exact)
                                                    .addComponent(nb_chiffre_grand)
                                                    .addComponent(nb_chiffre_petit)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(down_chiffre_2, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(valeur_chiffre_1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(up_chiffre_1)
                                                .addGap(42, 42, 42)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(up_chiffre_2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(valeur_chiffre_2, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(up_chiffre_3)
                                                .addGap(23, 23, 23))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(down_chiffre_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(valeur_chiffre_3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(valeur_chiffre_4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(test)
                                                .addGap(27, 27, 27))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(nb_tentatives_restantes)
                                                    .addComponent(up_chiffre_4)
                                                    .addComponent(down_chiffre_4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(157, Short.MAX_VALUE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_lbl_chiffretropbas)
                                    .addComponent(txt_lbl_chiffresexact)
                                    .addComponent(txt_lbl_chiffretrophaut))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(recommencer)
                                .addGap(64, 64, 64))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(texte_intro, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(165, 165, 165))
                        );
                        layout.setVerticalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(texte_intro)
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(up_chiffre_1)
                                    .addComponent(up_chiffre_2)
                                    .addComponent(up_chiffre_3)
                                    .addComponent(up_chiffre_4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(valeur_chiffre_1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(valeur_chiffre_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(valeur_chiffre_3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(valeur_chiffre_4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(test)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(down_chiffre_1)
                                            .addComponent(down_chiffre_3)
                                            .addComponent(down_chiffre_4))
                                        .addGap(33, 33, 33)
                                        .addComponent(nb_tentatives_restantes))
                                    .addComponent(down_chiffre_2))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_lbl_chiffresexact)
                                    .addComponent(nb_chiffre_exact))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(score, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                        .addGap(30, 30, 30)
                                        .addComponent(recommencer)
                                        .addGap(27, 27, 27))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txt_lbl_chiffretrophaut)
                                            .addComponent(nb_chiffre_grand))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txt_lbl_chiffretropbas)
                                            .addComponent(nb_chiffre_petit))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        );

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        // TODO add your handling code here:
        incrementDigit(0);
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        // TODO add your handling code here:
        incrementDigit(1);
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
        // TODO add your handling code here:
        incrementDigit(2);
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
        // TODO add your handling code here:
        incrementDigit(3);
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        // TODO add your handling code here:
        decrementDigit(0);
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
        // TODO add your handling code here:
        decrementDigit(1);
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
        // TODO add your handling code here:
        decrementDigit(2);
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
        // TODO add your handling code here:
        decrementDigit(3);
    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testActionPerformed
        // TODO add your handling code here:
       
         
        
    }//GEN-LAST:event_testActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new métier().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JLabel nb_chiffre_exact;
    private javax.swing.JLabel nb_chiffre_grand;
    private javax.swing.JLabel nb_chiffre_petit;
    private javax.swing.JLabel nb_tentatives_restantes;
    private javax.swing.JButton recommencer;
    private javax.swing.JLabel score;
    private javax.swing.JButton test;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel txt_lbl_chiffresexact;
    private javax.swing.JLabel txt_lbl_chiffretropbas;
    private javax.swing.JLabel txt_lbl_chiffretrophaut;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    private javax.swing.JLabel valeur_chiffre_1;
    private javax.swing.JLabel valeur_chiffre_2;
    private javax.swing.JLabel valeur_chiffre_3;
    private javax.swing.JLabel valeur_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
